modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="MoloX"
logoFile = "logo.png"
description='''
可以让你用望远镜在地图上标记兴趣点，
同时支持在Distant Horizons的远距离LOD区块标记兴趣点。
Allows you to use a spyglass to mark locations on your map,
and also supports marking waypoints within Distant Horizons' LOD chunks.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="distanthorizons"
type="required"
versionRange="[3.0.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="xaerominimap"
type="required"
versionRange="[25.3.13,)"
ordering="NONE"
side="BOTH"